############## server ##############
server:
  port: 9090 
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false

############## logging ##############
logging:
  level:
    root: WARN 
    org:
      springframework:
        web: INFO 
        security: INFO 
  file: log/worm.log

############## auth ##############
auth:
  protocol: http
  host: localhost
  port: 8091

############## api ##############
api:
  protocol: http
  host: localhost
  port: 8090
  context: /api


############## file ##############
file:
  salt: windows10
  tmpFolder: 

############## eureka ##############
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

############## spring ##############
spring:
  profiles:
    active: test
    
############## keystore ##############
keystore:
  clientCert: 
    file: webUI.jks
    password: webUIwebUI
    alias: mykey
  