logging:
  level:
    org:
      ll: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG
        
server:
  contextPath: /client

spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      clientId: test-client
      clientSecret: secret
      accessTokenUri: http://${api.host}:${api.port}/oauth/token
      userAuthorizationUri: http://${api.domain}:${api.port}/oauth/authorize
    resource:
      userInfoUri: http://${api.host}:${api.port}/me
      
api:
  client:
    clientId: api_client
    clientSecret: secret
    accessTokenUri: http://${auth.host}:${auth.port}/oauth/token
    userAuthorizationUri: http://${auth.host}:${auth.port}/oauth/authorize
    username: u
    password: p
  resource:
      userInfoUri: http://${api.host}:${api.port}/api/me


#facebook.client.clientId=233668646673605
#facebook.client.clientSecret=33b17e044ee6a4fa383f46ec6e28ea1d
#facebook.client.accessTokenUri=https://graph.facebook.com/oauth/access_token
#facebook.client.userAuthorizationUri=https://www.facebook.com/dialog/oauth
#facebook.client.tokenName=oauth_token
#facebook.client.authenticationScheme=query
#facebook.client.clientAuthenticationScheme=form
#facebook.resource.userInfoUri=https://graph.facebook.com/me

#github.client.clientId=bd1c0a783ccdd1c9b9e4
#github.client.clientSecret=1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#github.client.accessTokenUri=https://github.com/login/oauth/access_token
#github.client.userAuthorizationUri=https://github.com/login/oauth/authorize
#github.client.clientAuthenticationScheme=form
#github.resource.userInfoUri=https://api.github.com/user

#server.port=8443
#server.ssl.key-store=classpath:worm.jks
#server.ssl.key-store-password=wormworm
#server.ssl.key-password=wormworm